batch         | Traceback (most recent call last):
batch         |   File "consume.py", line 90, in <module>
batch         |     consume_queue()
batch         |   File "consume.py", line 81, in consume_queue
batch         |     bootstrap_servers=['kafka:9092']
batch         |   File "/usr/local/python/lib/python3.5/site-packages/kafka/consumer/group.py", line 182, in __init__
batch         |     self.config['api_version'] = self._client.check_version()
batch         |   File "/usr/local/python/lib/python3.5/site-packages/kafka/client_async.py", line 629, in check_version
batch         |     connect(node_id)
batch         |   File "/usr/local/python/lib/python3.5/site-packages/kafka/client_async.py", line 592, in connect
batch         |     raise Errors.NodeNotReadyError(node_id)
batch         | kafka.common.NodeNotReadyError: None
batch exited with code 1
